spring.application.name=HotelKiosk

spring.config.import=optional:file:.env[.properties]

# database
spring.datasource.mariadb.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.mariadb.url=jdbc:mariadb://localhost:3306/hotel_kiosk
spring.datasource.mariadb.username=${DATA_SOURCE_USER_NAME}
spring.datasource.mariadb.password=${DATA_SOURCE_USER_PASSWORD}

# logging
logging.level.org.springframework=info
logging.level.hotel_kiosk=debug
# logging pattern
logging.pattern.console=%clr(%-5level){green} %clr(%logger{36}.%M\\(\\)){cyan}: %msg%n

# mybatis
# 매퍼 파일의 위치 (resources/mapper 폴더 내의 모든 xml 인식)
mybatis.mapper-locations=classpath:mapper/**/*.xml
# 카멜 케이스 자동 매핑
mybatis.configuration.map-underscore-to-camel-case=true

# Thymeleaf 캐시 비활성화 (기본값은 false)
spring.thymeleaf.cache=false

# 정적 리소스(CSS, JS 등) 변경 시 즉시 반영을 위한 설정
spring.web.resources.cache.period=0

# session 설정
# 2시간 후 자동 세션 만료 (기본값은 2시간)
server.servlet.session.timeout=2h
# 브라우저 종료 시 세션 쿠키 삭제
server.servlet.session.cookie.max-age=-1

# Mail 발송
spring.mail.protocol=smtp
spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.ssl.enabled=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 인증번호 발송
spring.data.redis.host=localhost
spring.data.redis.port=6379

# toss
my.toss.widgetClientKey=${TOSS_CLIENT_KEY}
my.toss.widgetSecretKey=${TOSS_SECRET_KEY}

# SMS (Solapi/Nurigo)
sms.api.key=${SMS_API_KEY}
sms.api.secret=${SMS_API_SECRET}
sms.api.phone=${SMS_API_PHONE}

# AI CHAT
# 테이블 자동 구성 여부
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.enabled=false
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.openai.api-key=${AI_CHAT_API_KEY}

# PGVector
spring.datasource.pgvector.driver-class-name=org.postgresql.Driver
spring.datasource.pgvector.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.pgvector.username=postgres
spring.datasource.pgvector.password=postgres
spring.autoconfigure.exclude=org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration